### ISSUE TITLE
crash when trying to publish spans (?)

### ISSUE THREAD

**Issue by schmurfy** [uptrace/uptrace-go#65]
We got an issue today at ~10h42 CET which caused an error:
![image](https://user-images.githubusercontent.com/2983/111778988-d04b8380-88b5-11eb-90d9-c2f947b94cdb.png)

I am not sure what happened at this time but crashing the whole process should never happen :(

**Comment by schmurfy** [comment]
Did you had an incident at this time ?
a coworker looked at the code and in https://github.com/uptrace/uptrace-go/blob/master/internal/post.go#L76 if postWithRetry attempts all fails the method will return `nil, nil` which will crash the caller.

**Comment by vmihailenco** [comment]
@schmurfy sorry :( I believe https://github.com/uptrace/uptrace-go/commit/9411db24034e9d4bf083ff83fbd761b3b1dfe817 fixed that problem. But it looks like you are still on the old version.

Should I back-port the fix to v0.7.7? I am not sure how you stay on the old version, because go mod is very eager to use the latest available version. But I definitely can release v0.7.8.

>Did you had an incident at this time ?

I believe we've deployed new rate limiter at that time. I guess that may cause some flux.

>should never happen :(

Agreed. `Restart=always` helps a lot if you are using systemd.

**Comment by schmurfy** [comment]
Hello and thanks for the answer, we can update to the latest release if it fixes the issue, there are no particular reason to stay behind we just did not have a look at it.
our services are restarted but we don't have replicas so it still can cause some interruption

**Comment by vmihailenco** [comment]
Yes, it is better to update to v0.19 - see [changelog](https://github.com/uptrace/uptrace-go/blob/master/CHANGELOG.md#v0190) for example. I am running that version for a couple of days now so it should be safe to update :)

AFAIR regarding OpenTelemetry the only change should be replacing go.opentelemetry.io/otel/label with go.opentelemetry.io/otel/attribute. Other user-facing APIs seems to be stable now.
